package ir.webold.framework.enums.exception;

import lombok.Getter;


@Getter
public enum ExceptionEnum {
    SUCCESS,
    NOTFOUND,
    NOTFOUNDBYID,
    NOTFOUNDALLBYID,
    NOTFOUNDROLE,
    NOTFOUNDUSER,
    SERVERDENY,
    NOTDEVELOP,
    INTERNALSERVER,
    NOTSAVE,
    NOTUPDATE,
    NOTDELETE,
    NOTDELETEBYID,
    NOTDELETEALL,
    TOKENEXPIRETIME,
    ACCOUNTENABLE,
    ACCOUNTEXPIRE,
    ACCOUNTLOCKED,
    LOGINFAILED,
    MAXIMUMLOGIN,
    ENVIREMENTNOTFOUNDE,
    REFRESHTOKENEXPIRETIME,
    DOUBLEROLEADDED,
    NOTFOUNDUSERINFORMATION,
    IPGORDERTYPENOTFOUND,
    IPGREFNUMBERNOTFOUND,
    IPGREFNUMBEREXPIRED,
    OLDPASSWORDNOTCORRECTED,
    JWTTOKENISNOTVALID,
    JWTTOKENISEXPIRED,
    NOTFOUNDAPPLICATION,
    NOTFOUNDMICROSERVICE,
    NOTFOUNDUSERAPPLICATION
}
